version: '3.3'

services:
  mariadb:
    image: mariadb:10.6.0-focal
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mariadb:/var/lib/mariadb/data
      - ./schemas:/docker-entrypoint-initdb.d


volumes:
  mariadb:

