spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/task_tracker
    username: user
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

  flyway:
    schemas: task_tracker

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false